### ISSUE TITLE
In content.js, "justUpdatedSettings" is always false

### ISSUE THREAD

**Issue by krisshadow** [MarcGuiselin/screen-shader#2]
```
chrome.storage.onChanged.addListener(changes => {
        if(changes.settings){
            if(justUpdatedSettings){
                justUpdatedSettings = false;
            }else{
                let newSettings = changes.settings.newValue;

                // If location changed get the sunset and sunrise times again
                if(whenJulian && (settings.latitude != newSettings.latitude || settings.longitude != newSettings.longitude || settings.hasLocation != newSettings.hasLocation))
                    whenJulian = 0;

                settings = newSettings;

                // Check if url is disabled
                CheckUrlMatchDisabled();

                // If screen shader or shaded scrollbar was disabled
                if(!settings.shadedScrollbar || !(typeof settings.enabled == 'boolean' ? settings.enabled : settings.enabled < now))
                    $html.classList.remove('ss-shaded-scrollbars');

                // Update shade as soon as possible
                if(!document.hidden)
                    window.requestAnimationFrame(UpdateShade);
            }
        }
});
```
Forgive me if I'm wrong, but you never set justUpdatedSettings to true. Its initial value is false, and it never gets set to true, so, therefore, the second conditional that checks to see if justUpdatedSettings is always going to go to the else clause and is thus a waste of space in the code? Were you going to set it to true at the end of the else clause?

(I've never touched JavaScript, so you can remove this post if I'm being utterly stupid.)

I did a grep to see all the instances this variable was mentioned. Here's the output:

```
$ find . -name "*.js" | xargs grep -n justUpdatedSettings
./src/scripts/content.js:51:        justUpdatedSettings = false,
./src/scripts/content.js:286:            if(justUpdatedSettings){
./src/scripts/content.js:287:                justUpdatedSettings = false;
```

**Comment by MarcGuiselin** [comment]
Haha. You're absolutely correct!

I did some digging and found that the variable was used in an earlier version of Screen Shader before I was using version control 💀

If you are curious about its purpose, there used to be a keyboard shortcut that allowed users to hold CTRL + ALT keys and use the mouse scroll wheel to turn the shade up or down, as shown below:

````js
window.addEventListener('mousewheel', e => {
    // Use mousewheel to affect shade opacity
    if (!shiftDown && ctrldown && altdown) {
        settings.opacity = Math.max(0, Math.min(1, settings.opacity + e.wheelDeltaY / 2000));
        chrome.storage.local.set({settings});
        justUpdatedSettings = true;
        window.requestAnimationFrame(UpdateShade);
        e.preventDefault();
    }
});
````

Running `chrome.storage.local.set({settings})` always triggers `chrome.storage.onChanged`; so setting `justUpdatedSettings = true` would prevent unnecessary updates to the shade element!

**Comment by MarcGuiselin** [comment]
Removed in https://github.com/MarcGuiselin/screen-shader/commit/0ccefd44f1219a7d72ab3357da41b2a6642acc03

This code improvement will be released in the next major version.
