### ISSUE TITLE
Getting white screen on youtube when full screen

### ISSUE THREAD

**Issue by TheYarin** [MarcGuiselin/screen-shader#3]
Hey! Thank you for your excellent browser extension! I use it every day 😆 

When watching youtube videos I sometimes get a white screen when putting the video in full screen mode, but the video keeps playing in the background.
When this happens, I usually try refreshing the page, hard refreshing, closing the tab and re-open it, etc. After a while of such attempts (and probably giving up and trying again later) the video finally works in full screen mode. It's not very deterministic, so I don't have "steps to reproduce" for you, sorry...
It seems that the height of the `<body>` is 0px. I tried fiddling with the CSS and saw this line by your extension:
![image](https://user-images.githubusercontent.com/15931306/146533221-3cc2eb22-8bb4-470d-8851-a2e8148b6530.png)

I traced it back to this source code:
https://github.com/MarcGuiselin/screen-shader/blob/2c098a7e3b60f28bfd79e69c905361d0271a7e97/src/scripts/content.js#L241

It seems that when this line appears (and more specifically, `position: relatve !important;`), the screen turns white. I confirmed this by opening another video on full screen that worked properly, and checking the CSS. This line was missing on the working video. Adding `position: relatve !important;` to its `<body>` element broke the full screen mode.

It's also worth mentioning that this happens even though I configured the extension to be disabled when browsing youtube.com 😞

**Comment by MarcGuiselin** [comment]
Thanks for figuring out what does this. I've been getting reports of this happening for a long time but couldn't ever replicate it.

That's a workaround for some websites that have visual elements that would show over the screen-shader overlay. It shouldn't activate on youtube, so I'm going to code an exception that will always disable it on the site.

I know the [Magic Actions for YouTube](https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif) extension also causes issues on YouTube when paired with Screen Shader. Uninstall that if you have it installed, it's definitely adware and might also be spyware. That developer has a long history of running intrusive ads on their user's device.

**Comment by TheYarin** [comment]
Good to know about "Magic Actions for Youtube". I'm using a similar extension, maybe it's colliding with Screen Shader as well.

But why is this workaround applied even when I disabled Screen Shader for youtube in the config?

**Comment by MarcGuiselin** [comment]
> Good to know about "Magic Actions for Youtube". I'm using a similar extension, maybe it's colliding with Screen Shader as well.

Let me know what the extension is so I can investigate. Chances are if I can fix it for that extension, I'll also fix problems with other extensions, not just youtube.

> But why is this workaround applied even when I disabled Screen Shader for youtube in the config?

Not sure what you mean. 

![image](https://user-images.githubusercontent.com/24906387/146619451-a9811852-e3e0-4464-b930-c944ada45e84.png)
If you are disabling Screen Shader with the menu toggle, that will only hide the screen shader overlay. Screen Shader will still run on youtube.com, that way if the user wants to enable the shade again, they won't need to reload all their tabs.

**Comment by TheYarin** [comment]
The extension I use: [Enhancer for YouTube™](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle)

Yes, I'm using the disabled button like this:
![image](https://user-images.githubusercontent.com/15931306/146621390-b8d5b0cc-7fe1-4663-ba17-69401925a3dc.png)

Shouldn't the workaround (and all DOM manipulation, if possible) only happen when this is enabled?

**Comment by MarcGuiselin** [comment]
Ideally however, in a few cases this isn't possible.

There's a white page flash bug that happens when some websites load slowly. To avoid this, Screen Shader gives the page a grey background before `chrome.storage.local.get(['settings'], ...)` executes its callback since this takes a few ms, which makes the white flash worse.

However, the function `ApplyZIndexFix`, responsible for the YouTube-breaking issue definitely could be run only if Screen Shader is enabled. I'll look into fixing this when I have spare time.

Thanks again for you help! Happy new year.

**Comment by TheYarin** [comment]
Thank **you**! Happy new year!

**Comment by TheYarin** [comment]
I don't want to rush you or anything, but do you think you'll get to fixing this any time soon? It's **really** annoying that I can't watch youtube videos in full screen.

**Comment by MarcGuiselin** [comment]
Yeah. Life got in the way and I forgot about this, sorry. Look out for version 2.0.90

**Comment by TheYarin** [comment]
Finally, thank you!!
